# Generated by Django 2.0.2 on 2018-04-02 13:24

import club_pages.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('club_history', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField(null=True)),
                ('team2', models.CharField(max_length=250)),
                ('venue', models.CharField(max_length=250)),
                ('fixture_type', models.CharField(choices=[('t20', 'T20'), ('test', 'Test'), ('oneday', 'One Day'), ('other', 'Other')], default='Type', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=club_pages.models.upload_player_image)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=250)),
                ('dob', models.DateField(null=True)),
                ('birth_place', models.CharField(max_length=250)),
                ('squad_no', models.IntegerField()),
                ('type', models.CharField(max_length=250)),
                ('bowling_style', models.CharField(max_length=250)),
                ('player_type', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=club_pages.models.upload_player_image)),
                ('odi_matches', models.IntegerField(default=0)),
                ('test_matches', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('average', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('total_wickets', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('description', models.CharField(default='SOME STRING', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=club_pages.models.upload_player_image)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('coach_name', models.CharField(max_length=250)),
                ('total_member', models.IntegerField()),
                ('Ranking', models.IntegerField()),
                ('logo', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=250)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_pages.Club')),
            ],
        ),
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Some String', max_length=250)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_pages.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_pages.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='club_pages.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_pages.Tournament'),
        ),
    ]
