# Generated by Django 2.0.2 on 2018-03-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='type',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
