# Generated by Django 2.0 on 2018-04-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0002_upcommingmatches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='UpCommingMatches',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='average',
            new_name='phone_no',
        ),
        migrations.RemoveField(
            model_name='player',
            name='catches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='odi_matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_runs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_wickets',
        ),
        migrations.RemoveField(
            model_name='player',
            name='type',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Ranking',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='team',
            name='total_member',
        ),
        migrations.AddField(
            model_name='player',
            name='Is_keeper',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=250),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_place',
            field=models.CharField(choices=[('pakistan', 'PAKISTAN'), ('india', 'INDIA'), ('canada', 'CANADA'), ('Australia', 'AUSTRALIA'), ('dubai', 'DUBAI')], default='Select from drop down', max_length=250),
        ),
    ]
