# Generated by Django 2.0.2 on 2018-03-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0002_fixture_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='type',
        ),
        migrations.AddField(
            model_name='fixture',
            name='fixture_type',
            field=models.CharField(choices=[('t20', 'T20'), ('test', 'Test'), ('oneday', 'One Day'), ('other', 'Other')], default='Type', max_length=50),
        ),
    ]
