# Generated by Django 2.0.2 on 2018-03-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0003_player_player_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='name',
        ),
    ]
