# Generated by Django 2.0.2 on 2018-03-22 14:07

import club_pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0003_auto_20180314_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=club_pages.models.upload_player_image)),
            ],
        ),
    ]
