# Generated by Django 2.0 on 2018-04-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0003_auto_20180414_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='match_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
