# Generated by Django 2.0.2 on 2018-03-06 16:10

import club_pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0004_auto_20180306_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=club_pages.models.upload_player_image),
        ),
    ]
