# Generated by Django 2.0.2 on 2018-03-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0005_player_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Latest_News',
            new_name='LatestNews',
        ),
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='odi_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='test_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_wickets',
            field=models.IntegerField(default=0),
        ),
    ]
