# Generated by Django 2.0.2 on 2018-03-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0005_auto_20180330_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='team2',
            field=models.CharField(max_length=250),
        ),
    ]
