# Generated by Django 2.0 on 2018-04-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0005_auto_20180414_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='fixture_type',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Is_keeper',
        ),
        migrations.AddField(
            model_name='topcategory',
            name='average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='topcategory',
            name='economy_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='topcategory',
            name='total_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topcategory',
            name='total_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topcategory',
            name='total_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topcategory',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club_pages.Tournament'),
        ),
        migrations.AddField(
            model_name='topcategory',
            name='year',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_place',
            field=models.CharField(choices=[('pakistan', 'PAKISTAN'), ('india', 'INDIA'), ('canada', 'CANADA'), ('Australia', 'AUSTRALIA'), ('dubai', 'DUBAI'), ('norway', 'NORWAY')], default='norway', max_length=250),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone_no',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_pages.PlayerType'),
        ),
    ]
