# Generated by Django 2.0 on 2018-04-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0006_auto_20180414_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='bowling_style',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_matches',
        ),
    ]
