# Generated by Django 2.0.2 on 2018-03-07 17:33

import club_pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0006_auto_20180307_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=club_pages.models.upload_player_image),
        ),
    ]
