# Generated by Django 2.0 on 2018-04-14 16:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0007_auto_20180414_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
