# Generated by Django 2.0.2 on 2018-03-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0007_auto_20180307_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='date',
            field=models.DateField(default=0),
        ),
    ]
