# Generated by Django 2.0.2 on 2018-03-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0008_latestnews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='date',
            field=models.DateField(),
        ),
    ]
