# Generated by Django 2.0 on 2018-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0008_auto_20180414_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='fixture_type',
            field=models.CharField(choices=[('t20', 'T20'), ('test', 'Test'), ('oneday', 'One Day'), ('other', 'Other')], default='t20', max_length=2),
        ),
    ]
