# Generated by Django 2.0 on 2018-04-19 12:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0009_fixture_fixture_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_data', models.CharField(choices=[('home', 'Home'), ('about', 'About')], default='home', max_length=250)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fixture',
            name='fixture_type',
            field=models.CharField(choices=[('t20', 'T20'), ('test', 'Test'), ('oneday', 'One Day'), ('other', 'Other')], default='t20', max_length=250),
        ),
    ]
