# Generated by Django 2.0.2 on 2018-03-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0009_auto_20180307_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestnews',
            name='date',
        ),
    ]
