# Generated by Django 2.0 on 2018-04-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0010_auto_20180419_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicdata',
            name='footer_col_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dynamicdata',
            name='footer_col_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dynamicdata',
            name='footer_col_3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
