# Generated by Django 2.0 on 2018-04-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0014_auto_20180419_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('font_awesome_icon_tag', models.CharField(max_length=10)),
                ('url', models.URLField()),
            ],
        ),
    ]
