# Generated by Django 2.0 on 2018-04-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0015_sociallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='title',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'twitter'), ('insta', 'InstaGram'), ('linkedin', 'LinkedIn')], default='facebook', max_length=50, unique=True),
        ),
    ]
