# Generated by Django 2.0 on 2018-04-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0016_auto_20180419_2039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialLinks',
            new_name='SocialLink',
        ),
    ]
