# Generated by Django 2.0 on 2018-04-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0017_auto_20180419_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='font_awesome_icon_tag',
            field=models.CharField(max_length=30),
        ),
    ]
