# Generated by Django 2.0 on 2018-05-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0019_sponser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponser',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
