# Generated by Django 2.0 on 2018-05-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_pages', '0020_sponser_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicdata',
            name='page_data',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('footer1', 'Footer1'), ('footer2', 'Footer2'), ('footer3', 'Footer3'), ('email', 'Email'), ('phone', 'Phone')], default='home', max_length=250),
        ),
    ]
